package utils

object WidgetUtils {

    /**
     * Checks if subtitle corresponds to a completed lesson widget.
     *
     * Strings are taken from official app de-compilation, version 6.17.3
     * for future reference you can find all string with running `cat` with `grep` on the extracted resources.arsc
     */
    fun isLessonCompleted(subtitle: String): Boolean {
        return subtitle in completedLessonSubtitles
    }

    private val completedLessonSubtitles = listOf(
        "نراك لاحقًا!",
        "পরে দেখা হবে!",
        "Brzy na viděnou!",
        "Bis später!",
        "Τα λέμε αργότερα!",
        "¡Nos vemos luego!",
        "À plus tard !",
        "फिर मिलेंगे!",
        "Viszlát később!",
        "Sampai nanti, ya!",
        "A più tardi!",
        "また今度ね！",
        "또 봐요!",
        "Tot snel!",
        "Widzimy się wkrótce!",
        "Até mais!",
        "Ne vedem mai târziu!",
        "Ещё увидимся!",
        "See you later!",
        "Vi ses senare!",
        "மீண்டும் சந்திப்போம்!",
        "తర్వాత కలుద్దాం",
        "เจอกันใหม่นะฮ้า!",
        "Kitakits!",
        "Görüşürüz!",
        "До зустрічі!",
        "Hẹn gặp lại bạn nhé!",
        "期待重逢！",
        "期待重逢！",

        "نرجو أن تعود إلينا قريبًا!",
        "আবার আসবেন!",
        "Brzy se vraťte!",
        "Komm bald wieder!",
        "Να επιστρέψεις σύντομα!",
        "¡Regresa pronto!",
        "Reviens vite !",
        "जल्द वापस आएँ!",
        "Térj vissza hamarosan!",
        "Segera kembali, ya!",
        "Torna presto!",
        "また戻ってきてね！",
        "곧 다시 돌아와줘요!",
        "Kom snel terug!",
        "Wróć do nas wkrótce!",
        "Volte logo!",
        "Revino în curând!",
        "До скорой встречи!",
        "Come back soon!",
        "Kom tillbaka snart!",
        "விரைவில் மீண்டும் வருக!",
        "త్వరలో తిరిగి రండి!",
        "ไว้กลับมาอีกนะจ๊ะ!",
        "Balik ka agad!",
        "Sonra yine gel!",
        "Повертайтеся швидше!",
        "Nhớ trở lại sớm nhé!",
        "早点回来！",
        "早點回來！",

        "أراك المرة القادمة!",
        "আবার দেখা হবে!",
        "Tak zase příště!",
        "Bis zum nächsten Mal!",
        "Τα λέμε την επόμενη φορά!",
        "¡Hasta la próxima!",
        "À très vite !",
        "अगली बार मिलने तक!",
        "Viszlát legközelebb!",
        "Sampai jumpa lagi!",
        "Alla prossima!",
        "また今度ね！",
        "다음 번까지 안녕!",
        "Tot de volgende keer!",
        "Do następnego!",
        "Até a próxima!",
        "Pe data viitoare!",
        "До скорого!",
        "Till next time!",
        "Tills nästa gång!",
        "மீண்டும் சந்திப்போம்!",
        "మళ్ళీసారి కలిసే వరకు సెలవు!",
        "เจอกันใหม่น้าา~",
        "Sa uulitin!",
        "Tekrar görüşmek üzere!",
        "До зустрічі!",
        "Hẹn sớm gặp lại!",
        "期待重逢！",
        "期待重逢！",

        "أحسنت!",
        "শাব্বাশ!",
        "Jde vám to od ruky!",
        "Richtig gute Leistung!",
        "Μπράβο σου!",
        "¡Sigue así!",
        "Bien joué !",
        "इसे जारी रखें!",
        "Így kell ezt csinálni!",
        "Nah, gitu dong!",
        "Fantastico!",
        "いい感じ！",
        "잘 하고 있어요!",
        "Goed bezig!",
        "Świetna robota!",
        "Parabéns!",
        "Bravo!",
        "Так держать!",
        "Way to go!",
        "Så ska det se ut!",
        "இதுதான் முன்னேற்றம்!",
        "ఇలానే కొనసాగిండి!",
        "ตุดยอดไปเลย!",
        "Ang galing!",
        "Bravo!",
        "Так тримати!",
        "Tiến lên nào!",
        "冲鸭！",
        "沖鴨！",

        "أنا أفتقدك بالفعل!",
        "বড্ড মিস করছি!",
        "Už teď mi chybíte!",
        "Du fehlst mir schon!",
        "Μου λείπεις ήδη!",
        "¡Ya te extraño!",
        "Tu me manques déjà !",
        "आपकी याद आने लगी है!",
        "Máris hiányzol!",
        "Sudah kangen saja!",
        "Mi manchi già!",
        "もう会いたいよ！",
        "벌써 보고싶어요!",
        "Ik mis je nu al!",
        "Już za Tobą tęsknię!",
        "Já estou com saudade!",
        "Deja mi-e dor de tine!",
        "Уже скучаю по вам!",
        "Miss you already!",
        "Saknar dig redan!",
        "பிரிவு இப்போதே வாட்டுகிறது!",
        "ఇప్పటికే మిస్ అవుతున్నాను!",
        "คิถุงอีกแย้ว!",
        "Miss na kita!",
        "Seni şimdiden özledim!",
        "Уже сумую за вами!",
        "Nhớ bạn quá à!",
        "已经开始想你了！",
        "已經開始想你了！",

        "تابع الاجتهاد!",
        "চালিয়ে যান!",
        "Jen tak dál!",
        "Bleib dran!",
        "Συνέχισε έτσι!",
        "¡No pares!",
        "Continue comme ça !",
        "ऐसे ही लगे रहें!",
        "Csak így tovább!",
        "Pertahankan!",
        "Continua così!",
        "この調子！",
        "계속 열심히 해보세요!",
        "Ga zo door!",
        "Tak trzymaj!",
        "Continue assim!",
        "Ține-o tot așa!",
        "Не сдавайтесь!",
        "Keep it up!",
        "Fortsätt så!",
        "தொடர்ந்து முன்னேறுங்கள்!",
        "ఇలానే కొనసాగిండి!",
        "อย่าเพิ่งหมดไฟนะ!",
        "Tuloy lang!",
        "Böyle devam!",
        "Не зупиняйтесь!",
        "Cố gắng lên!",
        "继续学嫑停！",
        "繼續學嫑停！",
    )
}